const BOOKING_STATUS = {
  KEEPING: 0,
  ACTIVE: 1,
  CLOSED: 2,
  CANCEL: 3,
};
const FINISH_DISTANCE = 100;
const CHANGE_DISTANCE = 100;

const REMAINING_MINUTE_TICKET = 30;
const CANCEL_FREE_BOOKING = 15;

module.exports = {
  BOOKING_STATUS,
  FINISH_DISTANCE,
  CHANGE_DISTANCE,
  REMAINING_MINUTE_TICKET,
  CANCEL_FREE_BOOKING,
};
