const BOOKING_STATUS = {
  KEEPING: 0,
  ACTIVE: 1,
  CLOSED: 2,
  CANCEL: 3,
};
const FINISH_DISTANCE = 100;
const CHANGE_DISTANCE = 100;
module.exports = { BOOKING_STATUS, FINISH_DISTANCE, CHANGE_DISTANCE };
